/**
 * Antilopay Payment Processor Node.js SDK
 * @module antilopay-node
 * @version 2.0.0
 * @author phyziyx
 * @license MIT
 *
 * This SDK is designed to be used in Node.js (or equivalent environments) only.
 * It is not designed to be used in the browser or in a webview.
 * The API documentation can be found at https://doc.antilopay.com/AntilopayAPI.pdf
 */

import axios, { type AxiosInstance, type AxiosResponse } from 'axios';
import crypto from 'crypto';

//
//
// Interfaces and Types
//
//

export type AntilopayPaymentType =
  'payment' | 'withdraw' | 'refund' | 'popup' | 'topup';
export type AntilopayTransactionStatus =
  | 'PENDING'
  | 'SUCCESS'
  | 'FAIL'
  | 'CANCEL'
  | 'EXPIRED'
  | 'CHARGEBACK'
  | 'REVERSED';
export type AntilopayRecurringPaymentStatus =
  | 'CREATED'
  | 'WAIT_CONFIRM'
  | 'ACTIVE'
  | 'ACTIVE_FAILED'
  | 'PROCESSING'
  | 'COMPLETE'
  | 'CANCEL'
  | 'PROVIDER_CANCEL'
  | 'ERROR';
/**
 * The frequency of a recurrent payment.
 * - 'WEEK' — every week
 * - 'MONTH' — every month
 * - 'QUARTER' — every 3 months
 * - 'YEAR' — every year
 */
export type AntilopayRecurringPaymentType =
  'WEEK' | 'MONTH' | 'QUARTER' | 'YEAR';
/**
 * The delay period before the first charge of a recurrent payment
 * with the 'SUBSCRIPTION' category.
 */
export type AntilopayRecurringDelayType =
  'DAY' | 'WEEK' | 'MONTH' | 'QUARTER' | 'YEAR';
/**
 * The category of a recurrent payment.
 * - 'PAYMENT_TEMPLATE' — an initial payment followed by a recurring charge.
 *   Works with card payments only.
 * - 'SUBSCRIPTION' — a subscription creation followed by recurring charges.
 *   Works with SBP payments only.
 */
export type AntilopayRecurringPaymentCategory =
  'PAYMENT_TEMPLATE' | 'SUBSCRIPTION';
export type AntilopayPaymentMethod =
  'CARD_RU' | 'CARD_BY' | 'SBP' | 'SBER_PAY' | 'ERIP' | 'QIWI';
export type AntilopaySteamTopupPayMethod = 'STEAM_TOPUP_SBP';
export type AntilopayPaymentCurrency = 'RUB';
export type AntilopayProductType = 'goods' | 'services';
export type AntilopayPayoutMethod =
  'CARD_RU' | 'QIWI' | 'CRYPTO_TRON_USDT' | 'STEAM' | 'SBP';
export type AntilopayFeeType = 'BALANCE' | 'ORDER';
export type AntilopayPayoutStatus =
  'PENDING' | 'WAIT_ANSWER' | 'FAIL' | 'COMPLETE';
export type AntilopaySteamTopupStatus =
  'PENDING' | 'SUCCESS' | 'FAIL' | 'CANCEL' | 'EXPIRED';

export interface IAntilopayBalance {
  available: number;
  blocked: number;
  withdraw: number;
}

export interface IAntilopayProjectBalanceResponse {
  project_identificator: string;
  rub: IAntilopayBalance;
  usd?: IAntilopayBalance;
}

/**
 * The response of the "[V2 Api] Запрос баланса Проекта(-ов)" request.
 * The balances are expressed in kopecks/cents as strings (some values may
 * still arrive as numbers).
 */
export interface IAntilopayBalanceV2 {
  available: string | number;
  blocked: string | number;
  withdraw: string | number;
}

export interface IAntilopayProjectBalanceResponseV2 {
  project_identificator: string;
  rub: IAntilopayBalanceV2;
  usd?: IAntilopayBalanceV2;
}

/**
 * The response of the "Запрос баланса Проекта(-ов)" request made
 * without a `project_identificator` — the balances of every project.
 */
export interface IAntilopayProjectBalancesResponse {
  balances: Array<IAntilopayProjectBalanceResponse>;
}

/**
 * The response of the "[V2 Api] Запрос баланса Проекта(-ов)" request made
 * without a `project_identificator` — the balances of every project.
 */
export interface IAntilopayProjectBalancesResponseV2 {
  balances: Array<IAntilopayProjectBalanceResponseV2>;
}

export type AntilopayWebhookResponse =
  | IAntilopayWebhookPaymentResponse
  | IAntilopayWebhookPayoutResponse
  | IAntilopayWebhookRefundResponse
  | IAntilopayWebhookTopupResponse;

export interface IAntilopayWebhookRefundResponse {
  type: 'refund';
  /**
   * The unique identifier for the refund, generated by Antilopay.
   */
  refund_id: string;
  /**
   * The unique identifier for the payment associated with this refund.
   */
  payment_id: string;
  /**
   * The status of the refund.
   */
  status: 'COMPLETE' | 'FAIL';
  /**
   * The amount of the refund.
   */
  amount: number;
  /**
   * The time the refund was created.
   */
  ctime: string;
}

export interface IAntilopayWebhookPayoutResponse {
  type: 'withdraw';
  /**
   * The unique identifier for the payment, generated by Antilopay.
   */
  withdraw_id: string;
  /**
   * The unique identifier for the payout, generated by the merchant.
   * May be absent if the payout was created without an `order_id`.
   */
  order_id?: string;
  /**
   * The time the payment was created.
   */
  ctime: string;
  /**
   * The status of the payment.
   */
  status: 'COMPLETE' | 'FAIL';
  /**
   * The amount of the payment.
   */
  amount: number;
  /**
   * The fee for the payment.
   */
  fee: number;
  /**
   * The currency of the payment.
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The commission deducted from the payment.
   */
  fee_type: AntilopayFeeType;
  /**
   * The payment method used for the payment.
   */
  provide_method: AntilopayPayoutMethod;
}

export interface IAntilopayWebhookPaymentResponse {
  type: 'payment';
  /**
   * The unique identifier for the payment, generated by Antilopay.
   */
  payment_id: string;
  /**
   * The unique order identifier for the payment, generated by the merchant.
   */
  order_id: string;
  /**
   * The time the payment was created.
   */
  ctime: string;
  /**
   * The amount of the payment.
   */
  amount: number;
  /**
   * The original amount of the payment.
   */
  original_amount: number;
  /**
   * The fee for the payment.
   */
  fee: number;
  /**
   * The status of the payment.
   */
  status: 'SUCCESS' | 'FAIL';
  /**
   * The currency of the payment.
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The product name of the payment.
   * This is used for display purposes only and does not affect the payment.
   */
  product_name: string;
  /**
   * The description of the payment.
   * This is used for display purposes only and does not affect the payment.
   */
  description: string;
  /**
   * The payment method used for the payment, if successful.
   */
  pay_method?: AntilopayPaymentMethod;
  /**
   * The payment details, if successful.
   */
  pay_data?: string;
  /**
   * The unique identifier for the recurrent payment, if applicable, generated by Antilopay.
   */
  recurrent_id?: string;
  /**
   * The IP address of the customer.
   */
  customer_ip: string;
  /**
   * The user agent of the customer.
   */
  customer_useragent: string;
  /**
   * Information about refunds for this payment.
   * Displayed if the payment has refunds.
   */
  refunds?: Array<IAntilopayRefund>;
  /**
   * The customer's details.
   */
  customer: IAntilopayCustomerData;
  /**
   * Merchant's technical information, maximum 255 characters.
   */
  merchant_extra: string;
}

export interface IAntilopayWebhookTopupResponse {
  /**
   * The type of the callback.
   * The documentation states the value is always 'topup', while the official
   * example uses 'popup' — both are accepted.
   */
  type: 'topup' | 'popup';
  /**
   * The unique identifier for the top-up, generated by Antilopay.
   */
  topup_id: string;
  /**
   * The unique identifier for the top-up, generated by the merchant.
   */
  order_id: string;
  /**
   * The time the top-up was created.
   */
  ctime: string;
  /**
   * The time the top-up was completed.
   */
  complete_time: string;
  /**
   * The amount paid for the top-up.
   */
  amount_paid: number;
  /**
   * The amount credited to the Steam account.
   */
  topup_amount: number;
  /**
   * The currency of the top-up.
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The login of the Steam account being topped up.
   */
  steam_account: string;
  /**
   * The fee for the top-up. The final value is computed once the status
   * becomes 'SUCCESS'.
   */
  fee: number;
  /**
   * The merchant's profit from the top-up. The final value is computed once
   * the status becomes 'SUCCESS'.
   */
  profit: number;
  /**
   * The description of the top-up.
   */
  description: string;
  /**
   * The payment method used for the top-up, if successful.
   */
  pay_method?: AntilopaySteamTopupPayMethod;
  /**
   * The IP address of the customer.
   */
  customer_ip?: string;
  /**
   * The user agent of the customer.
   */
  customer_useragent?: string;
  /**
   * The customer's details.
   */
  customer: IAntilopayCustomerData;
}

export interface IAntilopayRefund {
  /**
   * The refund identifier.
   */
  refund_id: string;
  order_id: string;
  amount: number;
  status: 'COMPLETE' | 'FAIL';
}

interface IAntilopayServiceConstructor {
  projectId: string;
  secretId: string;
  secretKey: string;
  callbackKey: string;
  /**
   * The secret key used to sign payout ("выплата") requests, as described in
   * the "Создание выплаты" section of the documentation.
   *
   * Falls back to `secretKey` when not provided.
   */
  withdrawSecretKey?: string;
  timeout?: number;
}

export interface IAntilopaySignatureCheckResponse {
  status: 'ok';
}

export type IAntilopayRecurringPaymentStatus = {
  recurrentId: string;
};

/**
 * The identifier of the recurrent payment to cancel.
 * Provide either `recurrentId` or `transactionId`, never both.
 */
export type IAntilopayRecurringPaymentCancel =
  | {
      recurrentId: string;
      transactionId?: never;
    }
  | {
      transactionId: string;
      recurrentId?: never;
    };

export interface IAntilopayRecurrentPaymentCancelResponse {}

export interface IAntilopayRecurringPaymentStatusResponse {
  recurrent_id: string;
  type: AntilopayRecurringPaymentType;
  count: number;
  status: AntilopayRecurringPaymentStatus;
  start_date: string;
  next_payment_date: string;
  end_date: string;
  pay_method: AntilopayPaymentMethod;
  pay_data: string;
  payments: Array<IAntilopayPaymentStatus>;
}

/**
 * The parameters shared by both recurrent payment categories.
 */
interface IAntilopayRecurrentPaymentIntentBase {
  /**
   * The periodicity of the recurrent charges.
   * - 'WEEK' — every week
   * - 'MONTH' — every month
   * - 'QUARTER' — every 3 months
   * - 'YEAR' — every year
   * @required
   */
  type: AntilopayRecurringPaymentType;
  /**
   * The number of charges to be made (including the initial payment).
   * For example, if the type is 'MONTH' and the payment_count is 3, then the
   * payment will be made every month for 3 months.
   * @required
   */
  payment_count: number;
}

/**
 * Recurrent payment parameters for the 'PAYMENT_TEMPLATE' category —
 * an initial payment followed by a recurring charge.
 * Works with card payments only.
 *
 * `delay` and `delay_type` are only accepted by the API for the
 * 'SUBSCRIPTION' category, so they are forbidden here.
 */
export interface IAntilopayRecurrentPaymentTemplateIntent extends IAntilopayRecurrentPaymentIntentBase {
  /**
   * The category of the recurrent payment.
   * - 'PAYMENT_TEMPLATE' — an initial payment followed by a recurring charge.
   *   Works with card payments only.
   * @optional
   * @default "PAYMENT_TEMPLATE"
   */
  category: 'PAYMENT_TEMPLATE';

  // /**
  //  * Not supported for PAYMENT_TEMPLATE.
  //  */
  // delay?: never;

  // /**
  //  * Not supported for PAYMENT_TEMPLATE.
  //  */
  // delay_type?: never;
}

export interface IAntilopayRecurrentSubscriptionIntent extends IAntilopayRecurrentPaymentIntentBase {
  /**
   * The category of the recurrent payment.
   * - 'SUBSCRIPTION' — a subscription creation followed by recurring charges.
   *   Works with SBP payments only.
   */
  category: 'SUBSCRIPTION';

  /**
   * The delay before the first charge.
   */
  delay: number;

  /**
   * The period of the delay before the first charge.
   */
  delay_type: AntilopayRecurringDelayType;
}

export type IAntilopayRecurrentPaymentIntent =
  | IAntilopayRecurrentPaymentTemplateIntent
  | IAntilopayRecurrentSubscriptionIntent;

export interface IAntilopayPaymentIntent {
  /**
   * The payment amount in your currency.
   * The amount must be a positive number.
   * Two decimal places are allowed.
   * @required
   */
  amount: number;
  /**
   * The order identifier for the payment.
   * The order identifier must be unique for each payment, maximum 100 characters.
   * @required
   */
  order_id: string;
  /**
   * The amount currency for the payment.
   * @required
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The name of the product or service being purchased.
   * This is used for display purposes only and does not affect the payment.
   * @required
   */
  product_name: string;
  /**
   * The type of product or service being purchased.
   * @required
   */
  product_type: AntilopayProductType;
  /**
   * The quantity of the product or service being purchased.
   * Minimum value is 1.
   * @optional
   * @default 1
   */
  product_quantity?: number;
  /**
   * The VAT rate for the payment.
   * Seems to be in %, possible values: 10, 22.
   * Mandatory if the merchant's tax system is OSNO.
   * @optional
   * @default 0
   */
  vat?: number;
  /**
   * The payment description.
   * This is used for display purposes only and does not affect the payment.
   * @required
   */
  description: string;
  /**
   * The URL to redirect the user to after the payment is completed successfully,
   * maximum 500 characters.
   * @optional
   */
  success_url?: string;
  /**
   * The URL to redirect the user to after the payment is cancelled or failed,
   * maximum 500 characters.
   * @optional
   */
  fail_url?: string;
  /**
   * Customer's details
   */
  customer: AntilopayCustomer;
  /**
   * The preferred payment methods for the payment, for example
   * ["CARD_RU", "SBP"]. Possible values: CARD_RU (card), CARD_BY (Belarus
   * bank card), SBER_PAY (SberPay), SBP (SBP), ERIP (ERIP).
   * The methods available to your project can be seen in your personal
   * cabinet or clarified with support.
   * @optional
   */
  prefer_methods?: AntilopayPaymentMethod[];
  /**
   * Merchant's technical information, maximum 255 characters.
   * @optional
   */
  merchant_extra?: string;
  /**
   * Additional parameters for the payment.
   * @optional
   */
  params?: IAntilopayPaymentIntentParams;
  /**
   * The details for the recurrent payment.
   *
   * A discriminated union on `category`: the default 'PAYMENT_TEMPLATE'
   * category (cards only) forbids `delay`/`delay_type`, while
   * `'SUBSCRIPTION'` (SBP only) requires them.
   * @optional
   */
  recurrent?: IAntilopayRecurrentPaymentIntent;
}

export interface IAntilopayPaymentIntentParams {
  /**
   * If NSPK is enabled, you receive a SBP link to perform the payments at.
   *
   * This applies only to projects with SBP payments enabled
   */
  direct_nspk?: boolean;
  /**
   * If captcha is enabled, the buyer will need to complete the CAPTCHA on the payment page.
   *
   * This applies only to projects with the "captcha" feature enabled.
   */
  use_captcha?: boolean;
  /**
   * Skip the success page: once the payment is successful the buyer is
   * redirected straight to the `success_url` of the payment.
   */
  skip_success_page?: boolean;
}

export class AntilopayError extends Error {}

/**
 * Thrown when Antilopay API responds with a non-success code or when an HTTP
 * transport error occurs. Contains the API `code`, a message and the raw data.
 */
export class AntilopayApiError extends AntilopayError {
  public readonly apiCode: number;
  public readonly apiMessage: string;
  public readonly data: any;
  /**
   * The value of the `X-Apay-Request-Id` response header, when present.
   * Reference it when contacting technical support.
   */
  public readonly requestId?: string | undefined;

  constructor(apiCode: number, message: string, data: any, requestId?: string) {
    super(message);

    this.apiCode = apiCode;
    this.apiMessage = message;
    this.data = data;
    this.requestId = requestId;

    // Set the prototype explicitly to maintain instanceof checks
    Object.setPrototypeOf(this, AntilopayApiError.prototype);
  }
}

/**
 * Thrown when the signature verification for a webhook fails.
 * Indicates that the webhook may not be legitimate!
 */
export class AntilopaySignatureError extends AntilopayError {
  constructor() {
    super('Invalid signature');
  }
}

export interface IAntilopayPayoutResponse {
  /**
   * Payment identifier, generated by Antilopay.
   */
  withdraw_id: string;
}

export interface IAntilopayPaymentStatus {
  payment_id: string;
  order_id: string;
  payment_url: string;
  ctime: string;
  amount: number;
  original_amount: number;
  fee: number;
  status: AntilopayTransactionStatus;
  currency: AntilopayPaymentCurrency;
  product_name: string;
  description: string;
  merchant_extra: string;
  /**
   * The payment method. Displayed when the payment succeeded or failed.
   */
  pay_method?: AntilopayPaymentMethod;
  /**
   * The payment details. Displayed when the payment succeeded or failed.
   */
  pay_data?: string;
  /**
   * The identifier of the recurrent payment, if the payment is a recurrent one.
   */
  recurrent_id?: string;
  /**
   * The IP address of the customer. Displayed when the payment succeeded or failed.
   */
  customer_ip?: string;
  /**
   * The user agent of the customer. Displayed when the payment succeeded or failed.
   */
  customer_useragent?: string;
  /**
   * The customer's details, provided when the payment was created.
   */
  customer: IAntilopayCustomerData;
  /**
   * Information about the refunds of the payment.
   * Displayed if the payment has refunds.
   */
  refunds?: Array<IAntilopayRefund>;
}

export interface IAntilopayPaymentStatusResponse extends IAntilopayPaymentStatus {}

interface IAntilopayPaymentIntentResponse {
  payment_id: string;
  payment_url: string;
}

type AntilopayPaymentIntentResponsePlain = IAntilopayPaymentIntentResponse & {
  direct_nspk: false;
};

type IAntilopayPaymentIntentResponseNSPK = IAntilopayPaymentIntentResponse & {
  direct_nspk: true;
  transaction_id: string;
};

export type AntilopayPaymentIntentResponse =
  AntilopayPaymentIntentResponsePlain | IAntilopayPaymentIntentResponseNSPK;

export interface IAntilopayPayout {
  /**
   * The unique identifier for the payout on the merchant's side,
   * maximum 100 characters.
   * @optional
   */
  order_id?: string;
  /**
   * The amount to be paid out.
   */
  amount: number;
  /**
   * The method of payout.
   */
  method: AntilopayPayoutMethod;
  /**
   * The withdrawal address. Depends on the specified `method`:
   * - For CARD_RU, this is the card number.
   * - For QIWI, this is the phone number.
   * - For CRYPTO_TRON_USDT, this is the wallet address.
   * - For STEAM, this is the Steam ID.
   * - For SBP, this is the recipient bank identifier and the recipient phone
   *   number separated by a colon, e.g. "1XXXXXXXXXXX:7XXXXXXXXXX" (the bank
   *   identifier comes from the `schema` field of
   *   https://qr.nspk.ru/proxyapp/c2bmembers.json without the "bank" prefix,
   *   the phone number is in international format without the "+" sign).
   */
  account: string;
  /**
   * The source of the payout commission:
   * - 'BALANCE' — from the project balance
   * - 'ORDER' — from the payout amount
   * @optional
   * @default "ORDER"
   */
  fee_type?: AntilopayFeeType;
  /**
   * The cardholder's full name, for payouts to cards.
   * @optional
   */
  card_holder?: string;
  /**
   * The merchant's comment for the payout. Displayed in the payout history
   * and the Excel export. From 1 to 1024 characters.
   * @optional
   */
  comment?: string;
}

export interface IAntilopayPayoutStatusResponse {
  withdraw_id: string;
  order_id: string;
  ctime: string;
  status: AntilopayPayoutStatus;
  amount: number;
  fee: number;
  fee_type: AntilopayFeeType;
  currency: AntilopayPaymentCurrency;
  provide_method: AntilopayPayoutMethod;
}

export interface IAntilopayPayoutRateResponse {
  /**
   * The USDT/RUB exchange rate.
   * The value -1 means the current rate is unavailable — retry later.
   */
  USDTRUB: number;
}

export interface IAntilopayRefundResponse {
  /**
   * The unique identifier for the refund, generated by Antilopay.
   */
  refund_id: string;
}

export interface IAntilopayReverseResponse extends IAntilopayRefundResponse {}

export interface IAntilopayRefundStatusResponse {
  /**
   * The unique identifier for the refund, generated by Antilopay.
   */
  refund_id: string;
  /**
   * The Merchant's unique identifier for the payment.
   */
  order_id: string;
  /**
   * The unique identifier for the payment associated with this refund.
   */
  payment_id: string;
  /**
   * The status of the refund.
   */
  status: AntilopayPayoutStatus;
  /**
   * The amount of the refund.
   */
  amount: number;
}

/**
 * The parameters of the "Создание пополнения" (Steam top-up) request.
 */
export interface IAntilopaySteamTopupIntent {
  /**
   * The amount to pay for the top-up.
   * @required
   */
  amount: number;
  /**
   * The amount credited to the Steam account.
   * @required
   */
  topup_amount: number;
  /**
   * The identifier of the top-up on the merchant's side.
   * Must be unique.
   * @required
   */
  order_id: string;
  /**
   * The amount currency for the top-up.
   * @required
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The login of the Steam account to top up, maximum 255 characters.
   * @required
   */
  steam_account: string;
  /**
   * The description of the top-up.
   * @required
   */
  description: string;
  /**
   * The URL to redirect the user to after the top-up is completed successfully,
   * maximum 255 characters.
   * @optional
   */
  success_url?: string;
  /**
   * The URL to redirect the user to after the top-up is cancelled or failed,
   * maximum 255 characters.
   * @optional
   */
  fail_url?: string;
  /**
   * Customer's details.
   * @required
   */
  customer: AntilopayCustomer;
}

/**
 * The response of the "Создание пополнения" (Steam top-up) request.
 */
export interface IAntilopaySteamTopupResponse {
  /**
   * The identifier of the top-up in the System.
   */
  topup_id: string;
  /**
   * The link to the top-up payment form.
   */
  payment_url: string;
}

/**
 * The response of the "Проверка статуса пополнения" (Steam top-up) request.
 */
export interface IAntilopaySteamTopupStatusResponse {
  /**
   * The identifier of the top-up in the System.
   */
  topup_id: string;
  /**
   * The identifier of the top-up on the merchant's side.
   */
  order_id: string;
  /**
   * The link to the top-up payment form.
   */
  payment_url: string;
  /**
   * The status of the top-up.
   */
  status: AntilopaySteamTopupStatus;
  /**
   * The time the top-up was created.
   */
  ctime: string;
  /**
   * The time the top-up was paid successfully.
   */
  complete_time: string;
  /**
   * The amount paid for the top-up.
   */
  amount_paid: number;
  /**
   * The amount credited to the Steam account.
   */
  topup_amount: number;
  /**
   * The currency of the top-up.
   */
  currency: AntilopayPaymentCurrency;
  /**
   * The login of the Steam account being topped up.
   */
  steam_account: string;
  /**
   * The fee for the top-up. The final value is computed once the status
   * becomes 'SUCCESS'.
   */
  fee: number;
  /**
   * The merchant's profit from the top-up. The final value is computed once
   * the status becomes 'SUCCESS'.
   */
  profit: number;
  /**
   * The description of the top-up.
   */
  description: string;
  /**
   * The payment method. Displayed when the payment succeeded or failed.
   */
  pay_method?: AntilopaySteamTopupPayMethod;
  /**
   * The IP address of the customer. Displayed when the payment succeeded or failed.
   */
  customer_ip?: string;
  /**
   * The user agent of the customer. Displayed when the payment succeeded or failed.
   */
  customer_useragent?: string;
  /**
   * The customer's details, provided when the top-up was created.
   */
  customer: IAntilopayCustomerData;
}

/**
 * The customer details for the payment.
 * You may provide either email or phone or both.
 */
export interface IAntilopayCustomer {
  /**
   * The customer's e-mail address. Required when `phone` is not provided.
   */
  email?: string;
  /**
   * The customer's phone number.
   * Format: +<country code><space><the rest of the digits>, e.g. "+7 1234567890".
   * Required when `email` is not provided.
   */
  phone?: string;
  /**
   * The customer's address.
   */
  address?: string;
  /**
   * The customer's IP address.
   */
  ipAddress?: string;
  /**
   * The customer's full name.
   */
  fullName?: string;
}

/**
 * The customer data as returned by the Antilopay API (payment status,
 * callbacks, ...). Every field is optional and may be `null`.
 */
export interface IAntilopayCustomerData {
  /**
   * The customer's e-mail address.
   */
  email?: string | null;
  /**
   * The customer's phone number.
   */
  phone?: string | null;
  /**
   * The customer's address.
   */
  address?: string | null;
  /**
   * The customer's IP address.
   */
  ip?: string | null;
  /**
   * The customer's full name.
   */
  fullname?: string | null;
}

//
//
// Classes
//
//

export class AntilopayCustomer implements IAntilopayCustomer {
  public email?: string;
  public phone?: string;
  public address?: string;
  public ipAddress?: string;
  public fullName?: string;

  constructor({
    email,
    phone,
    address,
    ipAddress,
    fullName,
  }: IAntilopayCustomer) {
    if (!email && !phone) {
      throw new Error('Either email or phone must be provided.');
    }

    this.email = email;
    this.phone = phone;
    this.address = address;
    this.ipAddress = ipAddress;
    this.fullName = fullName;
  }

  public toJSON() {
    return {
      email: this.email,
      phone: this.phone,
      address: this.address,
      ip: this.ipAddress,
      fullname: this.fullName,
    };
  }
}

export class AntilopayService {
  private static instance: AntilopayService | null = null;

  /**
   * This array contains the endpoints that require a different signing key for payouts.
   * This was seemingly added in API version 1.52 (25.09.2026) - may require correction.
   */
  private static WITHDRAW_ENDPOINTS = [
    'withdraw/create',
    'signature/withdraw/check',
  ];

  private static readonly DEFAULT_BASE_URL = 'https://lk.antilopay.com/api/v1';

  /**
   * The base URL for the Antilopay API.
   * @default "https://lk.antilopay.com/api/v1"
   */
  private baseUrl: string = AntilopayService.DEFAULT_BASE_URL;

  /**
   * The API version for the Antilopay API.
   * @default 1
   */
  private apiVersion: number = 1;

  /**
   * The signing version for the Antilopay API.
   *
   * Used in the API header 'X-Apay-Sign-Version'.
   * @default 1
   */
  private signingVersion: number = 1;

  /**
   * The maximum amount of time (in milliseconds) that the client should wait for a response
   * before timing out a request.
   *
   * @unit milliseconds
   * @default 30_000
   */
  timeout?: number | undefined = 30_000;

  /**
   * The signing algorithm for the Antilopay API.
   *
   * The output produced by the signing algorithm is used to sign the API request
   * and is used in the API header 'X-Apay-Sign'.
   * @default "RSA-SHA256"
   */
  private signingAlgorithm: string = 'RSA-SHA256';
  /**
   * The output format for the signing algorithm.
   * @default "base64"
   */
  private signingAlgorithmOutput: crypto.BinaryToTextEncoding = 'base64';

  /**
   * The project ID for the Antilopay account.
   *
   * This is used to identify the account when making API requests.
   * Used in the API header 'X-Apay-Project-Id'.
   */
  private projectId: string = '';
  /**
   * The secret ID for the Antilopay account.
   *
   * This is provided by Antilopay and known as the merchant ID.
   * Used in the API header 'X-Apay-Secret-Id'.
   */
  private secretId: string = '';
  /**
   * Antilopay uses RSA keys.  This is a PEM formatted private key.
   *
   * This is used to sign the API requests. This is provided by Antilopay and should be kept secret.
   * @example "-----BEGIN RSA PRIVATE KEY-----\n<SECRET KEY>\n-----END RSA PRIVATE KEY-----"
   */
  private secretKey: string = '';
  /**
   * Antilopay uses RSA keys.  This is a PEM formatted public key.
   *
   * This is used to verify the Webhook signature. This is provided by Antilopay and should be kept secret.
   * @example "-----BEGIN PUBLIC KEY-----\n<PUBLIC KEY>\n-----END PUBLIC KEY-----"
   */
  private callbackKey: string = '';

  /**
   * The secret key used to sign payout ("выплата") requests, as described in
   * the "Создание выплаты" section of the documentation.
   *
   * Falls back to `secretKey` when it is not set.
   * @example "-----BEGIN RSA PRIVATE KEY-----\n<WITHDRAW SECRET KEY>\n-----END RSA PRIVATE KEY-----"
   */
  private withdrawSecretKey: string = '';

  /**
   * The value of the `X-Apay-Request-Id` header of the most recent response
   * received from the API. Reference it when contacting technical support.
   */
  private lastRequestId?: string | undefined = undefined;

  // Axios instance used for all HTTP requests
  private axiosInstance?: AxiosInstance;
  private interceptorsAttached: boolean = false;

  private constructor() {}

  /**
   * Get the instance of the AntilopayService.
   * @returns {AntilopayService}
   */
  public static getInstance(): AntilopayService {
    if (!this.instance) {
      this.instance = new AntilopayService();
    }

    return this.instance;
  }

  /**
   * Lazy getter for the axios instance. Ensures base URL, timeout and interceptors
   * are configured with the current service settings.
   */
  private getAxios(): AxiosInstance {
    if (!this.axiosInstance) {
      this.axiosInstance = axios.create({
        baseURL: this.baseUrl,
        timeout: this.timeout,
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
      });

      this.attachInterceptors();
    } else {
      // keep instance in sync with possibly updated config
      this.axiosInstance.defaults.baseURL = this.baseUrl;
      this.axiosInstance.defaults.timeout = this.timeout;
    }

    return this.axiosInstance;
  }

  /**
   * Attach request and response interceptors to the axios instance.
   */
  private attachInterceptors(): void {
    if (!this.axiosInstance || this.interceptorsAttached) return;

    // Request interceptor: merge API headers and compute signature when needed
    this.axiosInstance.interceptors.request.use(
      (config) => {
        config.headers = config.headers || {};

        const payload = config.data;
        const url = typeof config.url === 'string' ? config.url : '';

        // Payout requests are signed with the dedicated payout secret key
        // (falls back to the merchant secret key when it is not set).
        const signingKey = AntilopayService.WITHDRAW_ENDPOINTS.some(
          (endpoint) => url.includes(endpoint),
        )
          ? this.withdrawSecretKey || this.secretKey
          : this.secretKey;

        // Compute and merge headers for this request
        const apiHeaders = this.getApiHeaders(
          payload && typeof payload === 'object' ? payload : undefined,
          signingKey,
        );

        for (const key of Object.keys(apiHeaders)) {
          config.headers[key] = apiHeaders[key as keyof typeof apiHeaders];
        }

        return config;
      },
      (error) => Promise.reject(error),
    );

    // Response interceptor: check API error codes and normalize transport errors
    this.axiosInstance.interceptors.response.use(
      (response: AxiosResponse) => {
        this.captureRequestId(response && response.headers);

        const data = response && (response.data as any);

        if (
          data &&
          typeof data === 'object' &&
          typeof data.code === 'number' &&
          data.code !== 0
        ) {
          // API-level error (business logic)
          const msg = data.error || 'Antilopay API returned an error';
          return Promise.reject(
            new AntilopayApiError(data.code, msg, data, this.lastRequestId),
          );
        }

        return response;
      },
      (error) => {
        // Transport / HTTP error
        if (error && error.response) {
          const resp = error.response as AxiosResponse;
          this.captureRequestId(resp.headers);

          const data = resp.data as any;
          const apiCode =
            data && typeof data.code === 'number' ? data.code : resp.status;
          const message =
            (data && data.error) || resp.statusText || 'Request failed';

          return Promise.reject(
            new AntilopayApiError(
              apiCode,
              message,
              data || { status: resp.status },
              this.lastRequestId,
            ),
          );
        }

        // Unknown error (e.g., network failure)
        return Promise.reject(
          new AntilopayApiError(-1, error?.message || 'Network error', null),
        );
      },
    );

    this.interceptorsAttached = true;
  }

  /**
   * Store the `X-Apay-Request-Id` header of a response, when present.
   */
  private captureRequestId(headers: unknown): void {
    if (!headers || typeof headers !== 'object') return;

    const source = headers as Record<string, unknown> & {
      get?: (name: string) => unknown;
    };

    let value: unknown;
    if (typeof source.get === 'function') {
      value = source.get('X-Apay-Request-Id');
    }
    if (value === undefined || value === null) {
      for (const key of Object.keys(source)) {
        if (key.toLowerCase() === 'x-apay-request-id') {
          value = source[key];
          break;
        }
      }
    }

    if (typeof value === 'string' && value.length > 0) {
      this.lastRequestId = value;
    }
  }

  /**
   * Initialise the Antilopay Service singleton with the credentials.
   * @param config The configuration for the Antilopay Service.
   */
  public init(config: IAntilopayServiceConstructor): void {
    this.projectId = config.projectId;
    this.secretId = config.secretId;
    this.secretKey = config.secretKey;
    this.callbackKey = config.callbackKey;
    this.withdrawSecretKey = config.withdrawSecretKey ?? '';

    if (config.timeout !== undefined) {
      this.timeout = config.timeout;
    }
    if (this.axiosInstance) {
      this.axiosInstance.defaults.timeout = this.timeout;
    }
  }

  /**
   * Set the secret key used to sign payout ("выплата") requests.
   * Falls back to the merchant secret key when it is not set.
   * @param key The PEM formatted private key used to sign payout requests.
   */
  public setWithdrawSecretKey(key: string): void {
    this.withdrawSecretKey = key;
  }

  /**
   * Get the secret key used to sign payout ("выплата") requests.
   * @returns The PEM formatted private key, or an empty string when unset.
   */
  public getWithdrawSecretKey(): string {
    return this.withdrawSecretKey;
  }

  /**
   * The value of the `X-Apay-Request-Id` header of the most recent response
   * received from the API. Reference it when contacting technical support.
   * @returns The request identifier, or undefined when no response arrived yet.
   */
  public getLastRequestId(): string | undefined {
    return this.lastRequestId;
  }

  /**
   * Set the base URL for the API.
   * @param url
   */
  public setBaseUrl(url: string): void {
    this.baseUrl = url;
    if (this.axiosInstance) this.axiosInstance.defaults.baseURL = url;
  }

  /**
   * Get the base URL for the API.
   * @returns
   */
  public getBaseUrl(): string {
    return this.baseUrl;
  }

  /**
   * Set the API version for the API.
   * @param version
   */
  public setApiVersion(version: number): void {
    this.apiVersion = version;
  }

  /**
   * Get the API version for the API.
   * @returns
   */
  public getApiVersion(): number {
    return this.apiVersion;
  }

  /**
   * Get the project ID for the API.
   * @returns
   */
  public getProjectId(): string {
    return this.projectId;
  }

  /**
   * Get the secret ID for the API.
   * @returns
   */
  public getSecretId(): string {
    return this.secretId;
  }

  /**
   * Get the API headers for the API.
   * @param payload The payload to sign, when a signature is required.
   * @param signingKey The private key used to sign the payload.
   * @returns
   */
  private getApiHeaders(
    payload?: object,
    signingKey?: string,
  ): Record<string, string | number> {
    let signature = '';

    if (payload) {
      signature = this.generateSignature(payload, signingKey);
    }

    return {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      'X-Apay-Secret-Id': this.secretId,
      ...(payload
        ? {
            'X-Apay-Sign-Version': this.signingVersion,
            'X-Apay-Sign': signature,
          }
        : {}),
    };
  }

  /**
   * Generate the signature for the API request.
   * This is used to authenticate the request with the Antilopay API.
   * @param payload The payload to sign, must a JSON object.
   * @param signingKey The private key to sign with, defaults to the merchant secret key.
   * @returns The signature for the API request.
   */
  private generateSignature(payload: object, signingKey?: string): string {
    const data = JSON.stringify(payload);

    const signature = crypto.createSign(this.signingAlgorithm);
    signature.update(data);
    signature.end();

    const sign = signature.sign(
      signingKey ?? this.secretKey,
      this.signingAlgorithmOutput,
    );
    return sign;
  }

  /**
   * Verify the signature for the API request locally.
   * @param payload The payload to verify, must be a JSON object.
   * @param signature The signature to verify, found in header as 'X-Apay-Callback'.
   * @returns {boolean} True if the signature is valid, false otherwise.
   */
  public async verifySignature(
    payload: object,
    signature: string,
  ): Promise<boolean> {
    const data = JSON.stringify(payload);

    const verify = crypto.createVerify(this.signingAlgorithm);
    verify.update(data);
    verify.end();

    return verify.verify(
      this.callbackKey,
      signature,
      this.signingAlgorithmOutput,
    );
  }

  /**
   * Verify the signature for the API request.
   * @param payload The payload to verify, must be a JSON object.
   * @returns {IAntilopaySignatureCheckResponse}
   */
  public async verifySignatureRemote(
    payload: object,
  ): Promise<IAntilopaySignatureCheckResponse> {
    return await this.post<IAntilopaySignatureCheckResponse>(
      `/signature/check`,
      payload,
    );
  }

  /**
   * Verify a signature with the payout secret key using the Antilopay API.
   * @param payload The payload to verify, must be a JSON object.
   * @returns {IAntilopaySignatureCheckResponse}
   */
  public async verifyWithdrawSignatureRemote(
    payload: object,
  ): Promise<IAntilopaySignatureCheckResponse> {
    return await this.post<IAntilopaySignatureCheckResponse>(
      `/signature/withdraw/check`,
      payload,
    );
  }

  /**
   * Create a payment intent with the Antilopay API.
   * @param paymentIntent The payment intent to create.
   * @returns The payment intent response.
   * @example
   * const paymentIntent = await AntilopayService.getInstance().createPaymentIntent({
   *   amount: 100,
   *   order_id: '1',
   *   currency: 'RUB',
   *   product_name: 'Test Product',
   *   product_type: 'goods',
   *   product_quantity: 1,
   *   vat: 0,
   *   description: 'Test Product',
   *   success_url: 'https://example.com/success',
   *   fail_url: 'https://example.com/fail',
   *   customer: new AntilopayCustomer({
   *     email: 'customer@example.com',
   *     fullName: 'John Doe',
   *     ipAddress: '127.0.0.1',
   *   }),
   *   prefer_methods: ['CARD_RU', 'SBP', 'SBER_PAY'],
   *   merchant_extra: 'Test Merchant Extra',
   *   params: {
   *     direct_nspk: true,
   *     use_captcha: false,
   *   },
   * });
   */
  public async createPaymentIntent(
    paymentIntent: IAntilopayPaymentIntent,
  ): Promise<AntilopayPaymentIntentResponse> {
    const payload = {
      ...paymentIntent,
      project_identificator: this.projectId,
    };

    const responseData = await this.post<AntilopayPaymentIntentResponse>(
      `/payment/create`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the payment status for a payment.
   * @param orderId The order identifier for the payment.
   * @returns {Promise<IAntilopayPaymentStatusResponse>} The payment status response.
   */
  public async getPaymentStatus(
    orderId: string,
  ): Promise<IAntilopayPaymentStatusResponse> {
    const payload = {
      project_identificator: this.projectId,
      order_id: orderId,
    };

    const responseData = await this.post<IAntilopayPaymentStatusResponse>(
      `/payment/check`,
      payload,
    );

    return responseData;
  }

  public async getRecurringPaymentStatus(
    data: IAntilopayRecurringPaymentStatus,
  ): Promise<IAntilopayRecurringPaymentStatusResponse> {
    const payload = {
      project_identificator: this.projectId,
      recurrent_id: data.recurrentId,
    };

    const responseData =
      await this.post<IAntilopayRecurringPaymentStatusResponse>(
        `/payment/recurrent/check`,
        payload,
      );

    return responseData;
  }

  public async cancelRecurringPayment(
    data: IAntilopayRecurringPaymentCancel,
  ): Promise<IAntilopayRecurrentPaymentCancelResponse> {
    const payload = {
      project_identificator: this.projectId,
      ...(data.recurrentId !== undefined
        ? { recurrent_id: data.recurrentId }
        : { transaction_id: data.transactionId }),
    };

    const responseData =
      await this.post<IAntilopayRecurrentPaymentCancelResponse>(
        `/payment/recurrent/cancel`,
        payload,
      );

    return responseData;
  }

  /**
   * Process the webhook response from Antilopay.
   * @param payload The payload to process, must be a JSON object.
   * @param signature The signature to verify, found in header as 'X-Apay-Callback'.
   * @throws {AntilopaySignatureError} If the signature is invalid.
   * @returns {Promise<AntilopayWebhookResponse>} The webhook response, if valid.
   */
  public async processWebhook(
    payload: object,
    signature: string,
  ): Promise<AntilopayWebhookResponse> {
    const response = await this.verifySignature(payload, signature);

    if (!response) {
      throw new AntilopaySignatureError();
    }

    return payload as AntilopayWebhookResponse;
  }

  /**
   * Create a payout with the Antilopay API.
   * @param payoutIntent The payout intent to create.
   * @returns {Promise<IAntilopayPayoutResponse>} The payout response.
   */
  public async createPayout(
    payoutIntent: IAntilopayPayout,
  ): Promise<IAntilopayPayoutResponse> {
    const payload = {
      ...payoutIntent,
      project_identificator: this.projectId,
    };

    const responseData = await this.post<IAntilopayPayoutResponse>(
      `/withdraw/create`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the payout status.
   * @param withdrawId The withdraw identifier for the payout.
   * Provide either `withdrawId` or `orderId` (at least one is required).
   * @param orderId The merchant's identifier for the payout.
   * @returns {Promise<IAntilopayPayoutStatusResponse>} The payout status response.
   * @throws {AntilopayError} When neither `withdrawId` nor `orderId` is provided.
   */
  public async getPayoutStatus(
    withdrawId?: string,
    orderId?: string,
  ): Promise<IAntilopayPayoutStatusResponse> {
    if (!withdrawId && !orderId) {
      throw new AntilopayError(
        'Either withdrawId or orderId must be provided.',
      );
    }

    const payload = {
      project_identificator: this.projectId,
      ...(withdrawId ? { withdraw_id: withdrawId } : {}),
      ...(orderId ? { order_id: orderId } : {}),
    };

    const responseData = await this.post<IAntilopayPayoutStatusResponse>(
      `/withdraw/check`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the payout rate.
   * @returns {Promise<IAntilopayPayoutRateResponse>} The payout rate response.
   */
  public async getPayoutRate(): Promise<IAntilopayPayoutRateResponse> {
    const responseData =
      await this.get<IAntilopayPayoutRateResponse>(`/withdraw/ratio`);
    return responseData;
  }

  /**
   * Create a refund for a payment.
   * @param transactionId The transaction identifier of the payment to refund.
   * @param orderId The merchant's identifier for the refund, maximum 100 characters.
   * Pass `undefined` when not needed.
   * @param amount The amount to refund.
   * @returns {Promise<IAntilopayRefundResponse>} The refund response.
   */
  public async createRefund(
    transactionId: string,
    orderId: string | undefined,
    amount: number,
  ): Promise<IAntilopayRefundResponse> {
    const payload = {
      project_identificator: this.projectId,
      transaction_id: transactionId,
      ...(orderId ? { order_id: orderId } : {}),
      amount,
    };

    const responseData = await this.post<IAntilopayRefundResponse>(
      `/refund/create`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the refund status.
   * @param refundId The refund identifier.
   * Provide either `refundId` or `orderId` (at least one is required).
   * @param orderId The merchant's identifier for the refund.
   * @returns {Promise<IAntilopayRefundStatusResponse>} The refund status response.
   * @throws {AntilopayError} When neither `refundId` nor `orderId` is provided.
   */
  public async getRefundStatus(
    refundId?: string,
    orderId?: string,
  ): Promise<IAntilopayRefundStatusResponse> {
    if (!refundId && !orderId) {
      throw new AntilopayError('Either refundId or orderId must be provided.');
    }

    const payload = {
      project_identificator: this.projectId,
      ...(refundId ? { refund_id: refundId } : {}),
      ...(orderId ? { order_id: orderId } : {}),
    };

    const responseData = await this.post<IAntilopayRefundStatusResponse>(
      `/refund/check`,
      payload,
    );

    return responseData;
  }

  /**
   * Cancel (reverse) a payment made on the same day.
   * @param transactionId The transaction identifier of the payment to cancel.
   * @param orderId The merchant's identifier for the cancellation, maximum 100 characters.
   * Pass `undefined` when not needed.
   * @returns {Promise<IAntilopayReverseResponse>} The cancellation response.
   */
  public async createReverse(
    transactionId: string,
    orderId?: string,
  ): Promise<IAntilopayReverseResponse> {
    const payload = {
      project_identificator: this.projectId,
      transaction_id: transactionId,
      ...(orderId ? { order_id: orderId } : {}),
    };

    const responseData = await this.post<IAntilopayReverseResponse>(
      `/reverse/create`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the balance of the configured project.
   * @returns {Promise<IAntilopayProjectBalanceResponse>} The project balance response.
   */
  public async getProjectBalance(): Promise<IAntilopayProjectBalanceResponse> {
    const payload = {
      project_identificator: this.projectId,
    };

    const responseData = await this.post<IAntilopayProjectBalanceResponse>(
      `/project/balance`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the balances of every project of the merchant.
   * @returns {Promise<IAntilopayProjectBalancesResponse>} The balances response.
   */
  public async getAllProjectBalances(): Promise<IAntilopayProjectBalancesResponse> {
    const responseData = await this.post<IAntilopayProjectBalancesResponse>(
      `/project/balance`,
      {},
    );

    return responseData;
  }

  /**
   * Get the V2 balance of the configured project.
   * The balances are expressed in kopecks/cents.
   * @param projectId The project to request the balance for, defaults to the configured one.
   * @returns {Promise<IAntilopayProjectBalanceResponseV2>} The V2 project balance response.
   */
  public async getProjectBalanceV2(
    projectId?: string,
  ): Promise<IAntilopayProjectBalanceResponseV2> {
    const payload = {
      project_identificator: projectId ?? this.projectId,
    };

    const responseData = await this.postTo<IAntilopayProjectBalanceResponseV2>(
      this.getV2BaseUrl(),
      `/project/balance`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the V2 balances of every project of the merchant.
   * The balances are expressed in kopecks/cents.
   * @returns {Promise<IAntilopayProjectBalancesResponseV2>} The V2 balances response.
   */
  public async getAllProjectBalancesV2(): Promise<IAntilopayProjectBalancesResponseV2> {
    const responseData = await this.postTo<IAntilopayProjectBalancesResponseV2>(
      this.getV2BaseUrl(),
      `/project/balance`,
      {},
    );

    return responseData;
  }

  /**
   * Check whether a Steam account can be topped up.
   * @param steamAccountId The login of the Steam account to top up.
   * @returns {Promise<boolean>} `true` when the account was found and can be
   * topped up (HTTP 200), `false` when it cannot be topped up (HTTP 404).
   * @throws {AntilopayApiError} On HTTP 400 (missing data), 403 (access
   * denied), 500 (server error) or any other unexpected failure. The HTTP
   * status is exposed as `apiCode`.
   */
  public async checkSteamAccount(steamAccountId: string): Promise<boolean> {
    const payload = {
      project_identificator: this.projectId,
      steam_account: steamAccountId,
    };

    try {
      await this.post(`/steam/account/check`, payload);
      return true;
    } catch (error) {
      if (error instanceof AntilopayApiError && error.apiCode === 404) {
        return false;
      }

      throw error;
    }
  }

  /**
   * Create a Steam account top-up with the Antilopay API.
   * @param topup The top-up to create.
   * @returns {Promise<IAntilopaySteamTopupResponse>} The top-up response.
   */
  public async createSteamTopup(
    topup: IAntilopaySteamTopupIntent,
  ): Promise<IAntilopaySteamTopupResponse> {
    const payload = {
      ...topup,
      project_identificator: this.projectId,
    };

    const responseData = await this.post<IAntilopaySteamTopupResponse>(
      `/steam/topup/create`,
      payload,
    );

    return responseData;
  }

  /**
   * Get the status of a Steam account top-up.
   * @param orderId The merchant's identifier for the top-up.
   * @returns {Promise<IAntilopaySteamTopupStatusResponse>} The top-up status response.
   */
  public async getSteamTopupStatus(
    orderId: string,
  ): Promise<IAntilopaySteamTopupStatusResponse> {
    const payload = {
      project_identificator: this.projectId,
      order_id: orderId,
    };

    const responseData = await this.post<IAntilopaySteamTopupStatusResponse>(
      `/steam/topup/check`,
      payload,
    );

    return responseData;
  }

  /**
   * Derive the V2 API base URL from the configured base URL.
   * @returns The V2 base URL ("https://lk.antilopay.com/api/v2" by default).
   */
  private getV2BaseUrl(): string {
    return this.baseUrl.replace('/api/v1', '/api/v2');
  }

  private async post<T>(endpoint: string, payload: object): Promise<T> {
    const client = this.getAxios();

    const response = await client.post(endpoint, payload as any);

    return response.data as T;
  }

  /**
   * POST against an explicit base URL (absolute URLs override the axios
   * base URL) — used by the V2 API.
   */
  private async postTo<T>(
    baseUrl: string,
    endpoint: string,
    payload: object,
  ): Promise<T> {
    const client = this.getAxios();
    const url = `${baseUrl.replace(/\/+$/, '')}${endpoint}`;

    const response = await client.post(url, payload as any);

    return response.data as T;
  }

  private async get<T>(endpoint: string): Promise<T> {
    const client = this.getAxios();

    const response = await client.get(endpoint as any);

    return response.data as T;
  }
}
